obj-y	+= context_gcc.o
obj-y	+= vector_gcc.o
obj-y	+= exception.o
obj-y	+= cpu_port_asm.o
obj-y	+= stack.o
obj-y	+= cpu_port.o
obj-y	+= interrupt.o
obj-y	+= gic.o
obj-y	+= timer.o
obj-y	+= timer_zcu102.o

subdir-ccflags-$(CONFIG_CC_OPTIMIZE_LIBS_FOR_SPEED) += -O2